<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'account_login' => [[], ['_controller' => 'App\\Controller\\AccountController::login'], [], [['text', '/login']], [], []],
    'account_logout' => [[], ['_controller' => 'App\\Controller\\AccountController::logout'], [], [['text', '/logout']], [], []],
    'account_register' => [[], ['_controller' => 'App\\Controller\\AccountController::register'], [], [['text', '/register']], [], []],
    'account_profile' => [[], ['_controller' => 'App\\Controller\\AccountController::profile'], [], [['text', '/account/profile']], [], []],
    'account_password' => [[], ['_controller' => 'App\\Controller\\AccountController::updatePassword'], [], [['text', '/account/password-update']], [], []],
    'account_index' => [[], ['_controller' => 'App\\Controller\\AccountController::myAccount'], [], [['text', '/account']], [], []],
    'ads_index' => [[], ['_controller' => 'App\\Controller\\AdController::index'], [], [['text', '/ads']], [], []],
    'ad_create' => [[], ['_controller' => 'App\\Controller\\AdController::create'], [], [['text', '/ads/new']], [], []],
    'ads_edit' => [['slug'], ['_controller' => 'App\\Controller\\AdController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'slug'], ['text', '/ads']], [], []],
    'ads_show' => [['slug'], ['_controller' => 'App\\Controller\\AdController::show'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/ads']], [], []],
    'ads_delete' => [['slug'], ['_controller' => 'App\\Controller\\AdController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'slug'], ['text', '/ads']], [], []],
    'hello' => [[], ['_controller' => 'App\\Controller\\HomeControllers::hello'], [], [['text', '/hello']], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomeControllers::index'], [], [['text', '/']], [], []],
    'user_show' => [['slug'], ['_controller' => 'App\\Controller\\UserController::index'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/user']], [], []],
];
