<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8wOlKCS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8wOlKCS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8wOlKCS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8wOlKCS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8wOlKCS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8wOlKCS',
    'container.build_id' => '0e699fa0',
    'container.build_time' => 1598548552,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8wOlKCS');
